### Obtener todas las tareas
GET http://127.0.0.1:8000/api/tareas/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjczMmNhOTY3MTNiMWRkMTcyMzg1MDg0Y2U5ZjQzODFhZDAwY2VjZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLXRhcmVhcy1lOWExMiIsImF1ZCI6ImFwaS10YXJlYXMtZTlhMTIiLCJhdXRoX3RpbWUiOjE3NzM3NzkyMzUsInVzZXJfaWQiOiI3aEhRbUR5QktpUVczeG9SaXNPSGdBa1JsN2sxIiwic3ViIjoiN2hIUW1EeUJLaVFXM3hvUmlzT0hnQWtSbDdrMSIsImlhdCI6MTc3Mzc3OTIzNSwiZXhwIjoxNzczNzgyODM1LCJlbWFpbCI6ImNocmlzdGlhbkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiY2hyaXN0aWFuQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.sAGoDpvW6UyakPIKlzXv0xKTwMhKeTwbFXOsf3cURVEwYudaSdBT0lJ7GuiBTutH-LVGiFr2qYBYUXuO72oSosQZ7kTbBPvx02UpSn0XIhhcCdGHIdaYMHp7k5ZnEODFXjqBAbx-8Cw-tVra9jyhAg6taBY27duDksQq8sRcYyGflF1_K3oyBE2gNXav0FZ4KI9LRkFwx7P_SHxGrxWXdXgYo9GEWuenWa9oW23XKjW1FQ1z4UkgtFK7zQL5gpD4ivKGHz9Tujy4kaOpO14jra-S5cUtsHAMwMEAfFM2xe78C7M3Zd6o45Yn9ZUTLfEYJqjzZeJXD6p96X09ft1r3A

### Crear una nueva tarea (POST)
POST http://127.0.0.1:8000/api/tareas/
Content-Type: application/json

{
    "titulo": "Tarea para probar el delete",
    "descripcion": "Probando delete",
    "estado": "Eliminado"
}

### Actualizar una tarea (PUT)
PUT http://127.0.0.1:8000/api/tareas/bdQFbeF8NBwoSFqXC4ky/
Content-Type: application/json

{
    "titulo": "Título editado dos veces
    ",
    "descripcion": "Esta descripción ha sido actualizada",
    "estado": "En Proceso"
}

### Borrar una tarea
DELETE http://127.0.0.1:8000/api/tareas/AMYnOY2pP6kX3zAfCNzS/

### 1. Registrar un nuevo usuario (POST)
POST http://127.0.0.1:8000/api/auth/registro/
Content-Type: application/json

{
    "email": "christian@gmail.com",
    "password": "123456"
}

### 2. Iniciar sesión para conseguir el Token (POST)
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "email": "christian@gmail.com",
    "password": "123456"
}

### 3. Crear una tarea USANDO EL TOKEN (POST)
POST http://127.0.0.1:8000/api/tareas/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjczMmNhOTY3MTNiMWRkMTcyMzg1MDg0Y2U5ZjQzODFhZDAwY2VjZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLXRhcmVhcy1lOWExMiIsImF1ZCI6ImFwaS10YXJlYXMtZTlhMTIiLCJhdXRoX3RpbWUiOjE3NzM3NzkyMzUsInVzZXJfaWQiOiI3aEhRbUR5QktpUVczeG9SaXNPSGdBa1JsN2sxIiwic3ViIjoiN2hIUW1EeUJLaVFXM3hvUmlzT0hnQWtSbDdrMSIsImlhdCI6MTc3Mzc3OTIzNSwiZXhwIjoxNzczNzgyODM1LCJlbWFpbCI6ImNocmlzdGlhbkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiY2hyaXN0aWFuQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.sAGoDpvW6UyakPIKlzXv0xKTwMhKeTwbFXOsf3cURVEwYudaSdBT0lJ7GuiBTutH-LVGiFr2qYBYUXuO72oSosQZ7kTbBPvx02UpSn0XIhhcCdGHIdaYMHp7k5ZnEODFXjqBAbx-8Cw-tVra9jyhAg6taBY27duDksQq8sRcYyGflF1_K3oyBE2gNXav0FZ4KI9LRkFwx7P_SHxGrxWXdXgYo9GEWuenWa9oW23XKjW1FQ1z4UkgtFK7zQL5gpD4ivKGHz9Tujy4kaOpO14jra-S5cUtsHAMwMEAfFM2xe78C7M3Zd6o45Yn9ZUTLfEYJqjzZeJXD6p96X09ft1r3A

{
    "titulo": "Tarea con API Segura",
    "descripcion": "Mi primera tarea usando JWT de Firebase"
}

### Subir la foto de perfil a cloudinary

POST http://127.0.0.1:8000/api/perfil/foto/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLXRhcmVhcy1lOWExMiIsImF1ZCI6ImFwaS10YXJlYXMtZTlhMTIiLCJhdXRoX3RpbWUiOjE3NzI0Njg5NzcsInVzZXJfaWQiOiI3aEhRbUR5QktpUVczeG9SaXNPSGdBa1JsN2sxIiwic3ViIjoiN2hIUW1EeUJLaVFXM3hvUmlzT0hnQWtSbDdrMSIsImlhdCI6MTc3MjQ2ODk3NywiZXhwIjoxNzcyNDcyNTc3LCJlbWFpbCI6ImNocmlzdGlhbkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiY2hyaXN0aWFuQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.hWLPmEEyktpV0FAaWW48rKkEZgu7bDTKbPGXCLRsB3uHbjYjSbQgWTWzXjVXbkZtdiBvR8kKTri6OQrZaSszjwWCv5rnkGiA2rmmMmogE0H5XvoE5xAAqtaa_HVwfwyPPjC7BASTTN_8khylqydZJbhuyqfMkQxGW3DYLa6hA9NIDPuO9BO2iChpz0k7WDPcf_QQWP77lJTzbRd5U-kQPs7UxvIbJZ8NCxWblCIUrG4wCMQknhB2Uy76Ji8EG3A4HMIPnX7MdM-16qyFet2YAiChreU343bukHW7X2b1aoDvVTaK1bFpao29ijEfAm3-A0Iu63JlUrI8BQA83XGV5g
Content-Type: multipart/form-data; boundary=MiBoundary

--MiBoundary
Content-Disposition: form-data; name="imagen"; filename="avatar.jpg"
Content-Type: image/jpeg

< /home/chris/Documents/api_adso/avatar.jpg
--MiBoundary--