### Obtener todas las tareas
GET http://127.0.0.1:8000/api/tareas/?limit=1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLXRhcmVhcy1lOWExMiIsImF1ZCI6ImFwaS10YXJlYXMtZTlhMTIiLCJhdXRoX3RpbWUiOjE3NzI3NDU5MzksInVzZXJfaWQiOiI3aEhRbUR5QktpUVczeG9SaXNPSGdBa1JsN2sxIiwic3ViIjoiN2hIUW1EeUJLaVFXM3hvUmlzT0hnQWtSbDdrMSIsImlhdCI6MTc3Mjc0NTkzOSwiZXhwIjoxNzcyNzQ5NTM5LCJlbWFpbCI6ImNocmlzdGlhbkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiY2hyaXN0aWFuQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.PlreyHpSlSRqGxi2q2aPJUwLzfgyexjJlIqjS3U1jYdFpgHmwc7mmsVI5CcSy6OFOPeeBUly7r1ny5LhcsnzRBC26ViE0sIq8UV8v--hRxugDvm1dDWkeKoPIkY_2nBV5dbwGRN4FlpWWnXA2Z5qSBGQw6wQoZLEJsb-rmZkW-u2RrdHzS_JPOD3e_VYZcXhLNSGMKQ3uhcQ3QIBjZjNiSpJtZG07bmwJnVXbPuW-ZuZFD9YW6-nWv0MGIiLlhzcUst_JRzcdvJBoQCczH0xi4_dNzOEU1jlad2xtnrHhVY4LLk48oY8k97TMpXHV45SIQj56ERUazAz4elPQzR_uA

### Crear una nueva tarea (POST)
POST http://127.0.0.1:8000/api/tareas/
Content-Type: application/json

{
    "titulo": "Tarea para probar el delete",
    "descripcion": "Probando delete",
    "estado": "Eliminado"
}

### Actualizar una tarea (PUT)
PUT http://127.0.0.1:8000/api/tareas/bdQFbeF8NBwoSFqXC4ky/
Content-Type: application/json

{
    "titulo": "Título editado dos veces
    ",
    "descripcion": "Esta descripción ha sido actualizada",
    "estado": "En Proceso"
}

### Borrar una tarea
DELETE http://127.0.0.1:8000/api/tareas/AMYnOY2pP6kX3zAfCNzS/

### 1. Registrar un nuevo usuario (POST)
POST http://127.0.0.1:8000/api/auth/registro/
Content-Type: application/json

{
    "email": "christian@gmail.com",
    "password": "123456"
}

### 2. Iniciar sesión para conseguir el Token (POST)
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "email": "christian@gmail.com",
    "password": "123456"
}

### 3. Crear una tarea USANDO EL TOKEN (POST)
POST http://127.0.0.1:8000/api/tareas/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLTI2OS01ZWFiOSIsImF1ZCI6ImFwaS0yNjktNWVhYjkiLCJhdXRoX3RpbWUiOjE3NzI1NjI0NTEsInVzZXJfaWQiOiIxaEpoTm42RFM3YTExTG5BdHo4cG1OOFhJOXAyIiwic3ViIjoiMWhKaE5uNkRTN2ExMUxuQXR6OHBtTjhYSTlwMiIsImlhdCI6MTc3MjU2MjQ1MSwiZXhwIjoxNzcyNTY2MDUxLCJlbWFpbCI6ImNocmlzdGlhbkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiY2hyaXN0aWFuQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.Gl61RLsLC4L3i1PUaCoToXZUJqv-hClePdXFA0Eo52Ze19Cy7pcz_l0PSNLubk7fg5G_iuNQ8pmNzI7lZppie2UZfmZB2Wo8HBr95wgMnoDfiOM-pyFzcaa308QYdo_bf3Vab1Y_ZZ62hNXyxLdcu0XdOy8Bln2Q_45MzhBFUpwJ89zQAvHnOQfuKWlIzkHkPxtLslhDRPUTZ3CCQgOgzTLtSzL32xBacdqkjWjYQfNAnpuURxCdUM5vhF8v3uOK_FDrAChaYeo9uuZ2jty8qUVFluO9C6OmkXnBNFGlbjdGpDQqbq7JGcNs7ulOHKC2hAwTVEtre1IBRJxmxZbxXQ

{
    "titulo": "Tarea con API Segura",
    "descripcion": "Mi primera tarea usando JWT de Firebase"
}

### Subir la foto de perfil a cloudinary

POST http://127.0.0.1:8000/api/perfil/foto/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLXRhcmVhcy1lOWExMiIsImF1ZCI6ImFwaS10YXJlYXMtZTlhMTIiLCJhdXRoX3RpbWUiOjE3NzI0Njg5NzcsInVzZXJfaWQiOiI3aEhRbUR5QktpUVczeG9SaXNPSGdBa1JsN2sxIiwic3ViIjoiN2hIUW1EeUJLaVFXM3hvUmlzT0hnQWtSbDdrMSIsImlhdCI6MTc3MjQ2ODk3NywiZXhwIjoxNzcyNDcyNTc3LCJlbWFpbCI6ImNocmlzdGlhbkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiY2hyaXN0aWFuQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.hWLPmEEyktpV0FAaWW48rKkEZgu7bDTKbPGXCLRsB3uHbjYjSbQgWTWzXjVXbkZtdiBvR8kKTri6OQrZaSszjwWCv5rnkGiA2rmmMmogE0H5XvoE5xAAqtaa_HVwfwyPPjC7BASTTN_8khylqydZJbhuyqfMkQxGW3DYLa6hA9NIDPuO9BO2iChpz0k7WDPcf_QQWP77lJTzbRd5U-kQPs7UxvIbJZ8NCxWblCIUrG4wCMQknhB2Uy76Ji8EG3A4HMIPnX7MdM-16qyFet2YAiChreU343bukHW7X2b1aoDvVTaK1bFpao29ijEfAm3-A0Iu63JlUrI8BQA83XGV5g
Content-Type: multipart/form-data; boundary=MiBoundary

--MiBoundary
Content-Disposition: form-data; name="imagen"; filename="avatar.jpg"
Content-Type: image/jpeg

< /home/chris/Documents/api_adso/avatar.jpg
--MiBoundary--